# Generated by Django 3.2.10 on 2022-01-22 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220121_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('qualification', models.TextField(null=True)),
                ('specialization', models.TextField(null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('experiance', models.FloatField(null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('extra_fields', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Hr',
        ),
    ]
