# Generated by Django 3.2.10 on 2022-01-23 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220123_0435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='experiance',
            new_name='experience',
        ),
    ]
