# Generated by Django 3.2.10 on 2022-02-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_experiance_candidate_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='qualification',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='specialization',
            field=models.TextField(default=None, null=True),
        ),
    ]
