# Generated by Django 3.2.10 on 2022-01-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='round1',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='round2',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='round3',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interview',
            name='scheduled_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
